### ISSUE TITLE
Error Feedback when modifying the graph

### ISSUE THREAD

**Issue by AqSlz** [danielgiampaolo/CIS4930_Python#11]
In renaming/addition of nodes/edges, there are various reasons why an operation might not succeed.

For example, when renaming, changing the name of a node to a name of an already existing node, causes the old name to stay.

I believe we should implement some feedback message system to tell the user when a specific modification fails.

**Comment by danielgiampaolo** [comment]
By adding the error items below to the session:
"node_error": request.session.get('node_error', ''),
"edge_error": request.session.get('edge_error', '')

I was able to report on conflicts within the add/del/update functions.
![node_error](https://user-images.githubusercontent.com/54381915/87882035-46b48080-c9cb-11ea-8a34-ae979d28457c.png)
