### ISSUE TITLE
Increase generated image size

### ISSUE THREAD

**Issue by surc54** [danielgiampaolo/CIS4930_Python#2]
Right now, the image generated by NetworkX is 640x480. Modify `image_builder.py` to increase the size of the image.

You may need to modify the styles in the frontend in order to properly display the image.

**Comment by surc54** [comment]
Image size increase in 5516aadc01097160eb63fdb228051cccee8719ed

Image collision with sidebar, med priority

**Comment by AqSlz** [comment]
Image size capped to window size. 
Collision solved. Sidebar no longer is positioned "fixed"
Image should always be to the right of the sidebar.
