### ISSUE TITLE
Weight support (per edge)

### ISSUE THREAD

**Issue by surc54** [danielgiampaolo/CIS4930_Python#6]

**Comment by surc54** [comment]
As mentioned in #5 ([this comment](https://github.com/danielgiampaolo/CIS4930_Python/issues/5#issuecomment-657071384)), if we are using **Link** as the weight, the `download_csv` method needs to be modified.

**Comment by EnzoEguesDo** [comment]
Wieght function implemented. Finalized UI not determined
