### ISSUE TITLE
Performance - Create routing algorithms

### ISSUE THREAD

**Issue by surc54** [danielgiampaolo/CIS4930_Python#7]
One of the features we plan to do are ___node routing algorithms___, which is just the fancy way of saying graph algorithms. This task has two components: frontend & backend.

The backend portion will be done in C to meet our performance requirement.

**Comment by ppgajjar** [comment]
i'll do this one.

**Comment by danielgiampaolo** [comment]
For establishing benchmarks, I implemented a shortest path setup in python, using NetworkX. Changes have been pushed to dg/shortestpath.

I included a drop-down of to/from nodes and updated the function in image_builder to handle paths.

![image](https://user-images.githubusercontent.com/54381915/88490637-f01ae980-cf6a-11ea-9fda-533dd01591d1.png)

**Comment by danielgiampaolo** [comment]
Integrated the path function with the interactive graph and latest front end.

![image](https://user-images.githubusercontent.com/54381915/88999368-5df44780-d2c2-11ea-8356-980038fd0609.png)
